#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LGnumberGen.Resource", IsApplication=true)]

namespace LGnumberGen
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040004
			public const int blue2 = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int blue25 = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int grey05 = 2130968582;
			
			// aapt resource value: 0x7f040002
			public const int orange4 = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int orange5 = 2130968579;
			
			// aapt resource value: 0x7f040007
			public const int white1 = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int white2 = 2130968584;
			
			// aapt resource value: 0x7f040000
			public const int yellow1 = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int yellow2 = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Copyright = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Copyrightblack = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int custombutton = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_home_white_24dp = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_launcher = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_open_in_browser_white_24dp = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_settings_white_24dp = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int mainLogo = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int mainLogoSmall = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070007
			public const int AddName = 2131165191;
			
			// aapt resource value: 0x7f070012
			public const int GenerateListNameEntry = 2131165202;
			
			// aapt resource value: 0x7f07000e
			public const int GeneratedList = 2131165198;
			
			// aapt resource value: 0x7f07001d
			public const int Load = 2131165213;
			
			// aapt resource value: 0x7f070029
			public const int MaxNumber = 2131165225;
			
			// aapt resource value: 0x7f070028
			public const int MinNumber = 2131165224;
			
			// aapt resource value: 0x7f070022
			public const int NameNumList = 2131165218;
			
			// aapt resource value: 0x7f07002a
			public const int NumberOfPicks = 2131165226;
			
			// aapt resource value: 0x7f07002e
			public const int Scroller1 = 2131165230;
			
			// aapt resource value: 0x7f070024
			public const int btnGenerateList = 2131165220;
			
			// aapt resource value: 0x7f070004
			public const int btnHome = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int btnLoadImg = 2131165189;
			
			// aapt resource value: 0x7f070010
			public const int btnReGenerateList = 2131165200;
			
			// aapt resource value: 0x7f070038
			public const int btnSaveSettings = 2131165240;
			
			// aapt resource value: 0x7f070006
			public const int btnSettingsImg = 2131165190;
			
			// aapt resource value: 0x7f07001f
			public const int buttonAddName = 2131165215;
			
			// aapt resource value: 0x7f07000c
			public const int buttonBack = 2131165196;
			
			// aapt resource value: 0x7f07000a
			public const int buttonCancelAdd = 2131165194;
			
			// aapt resource value: 0x7f07002b
			public const int buttonGen = 2131165227;
			
			// aapt resource value: 0x7f070015
			public const int buttonNamedNumListToggle = 2131165205;
			
			// aapt resource value: 0x7f070014
			public const int buttonNumberListToggle = 2131165204;
			
			// aapt resource value: 0x7f07002d
			public const int buttonSave = 2131165229;
			
			// aapt resource value: 0x7f07001e
			public const int buttonSettingMain = 2131165214;
			
			// aapt resource value: 0x7f07000d
			public const int buttonShare = 2131165197;
			
			// aapt resource value: 0x7f07002c
			public const int buttonShareN = 2131165228;
			
			// aapt resource value: 0x7f070020
			public const int buttonsaveNamedNumList = 2131165216;
			
			// aapt resource value: 0x7f070008
			public const int centerPoint = 2131165192;
			
			// aapt resource value: 0x7f070013
			public const int centerPoint2 = 2131165203;
			
			// aapt resource value: 0x7f070011
			public const int chkActive = 2131165201;
			
			// aapt resource value: 0x7f070031
			public const int colourText = 2131165233;
			
			// aapt resource value: 0x7f070018
			public const int deleteText = 2131165208;
			
			// aapt resource value: 0x7f07002f
			public const int generatedNumbers = 2131165231;
			
			// aapt resource value: 0x7f070023
			public const int hiddenGuid = 2131165219;
			
			// aapt resource value: 0x7f07000b
			public const int hiddenGuid2 = 2131165195;
			
			// aapt resource value: 0x7f070030
			public const int hiddenGuid3 = 2131165232;
			
			// aapt resource value: 0x7f07000f
			public const int hiddenGuidNew = 2131165199;
			
			// aapt resource value: 0x7f07001a
			public const int imageView1 = 2131165210;
			
			// aapt resource value: 0x7f07003a
			public const int imageView2 = 2131165242;
			
			// aapt resource value: 0x7f070017
			public const int listLoads = 2131165207;
			
			// aapt resource value: 0x7f070026
			public const int listNameEntry = 2131165222;
			
			// aapt resource value: 0x7f070019
			public const int loadName = 2131165209;
			
			// aapt resource value: 0x7f070039
			public const int logoText = 2131165241;
			
			// aapt resource value: 0x7f070027
			public const int nameId = 2131165223;
			
			// aapt resource value: 0x7f07001c
			public const int namedNumGen = 2131165212;
			
			// aapt resource value: 0x7f07001b
			public const int numGen = 2131165211;
			
			// aapt resource value: 0x7f070035
			public const int radioBlue = 2131165237;
			
			// aapt resource value: 0x7f070033
			public const int radioDefault = 2131165235;
			
			// aapt resource value: 0x7f070037
			public const int radioGreen = 2131165239;
			
			// aapt resource value: 0x7f070032
			public const int radioGroupColour = 2131165234;
			
			// aapt resource value: 0x7f070034
			public const int radioPurple = 2131165236;
			
			// aapt resource value: 0x7f070036
			public const int radioRed = 2131165238;
			
			// aapt resource value: 0x7f070000
			public const int relativeLayout1 = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int relativeLayout2 = 2131165186;
			
			// aapt resource value: 0x7f070009
			public const int saveName = 2131165193;
			
			// aapt resource value: 0x7f070021
			public const int selectedNumber = 2131165217;
			
			// aapt resource value: 0x7f070025
			public const int selectedText = 2131165221;
			
			// aapt resource value: 0x7f070016
			public const int textView1 = 2131165206;
			
			// aapt resource value: 0x7f070001
			public const int toolbarSelection = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int toolbarSelectionTitle = 2131165187;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddName = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int GeneratedList = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int GeneratedListSelection = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int loadList = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int loadListSelection = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int namedNumGen = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int NamedNumSelection = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int numGen = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Settings = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int SplashLayout = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060002
			public const int Theme_BlueTheme = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int Theme_GreenTheme = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Theme_MyTheme = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int Theme_PurpleTheme = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int Theme_RedTheme = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int Theme_Splash = 2131099653;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
